import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import StoreProvider from './StoreProvider';
import './globals.css';

const inter = Source_Sans_3({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Fuel App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang='en'>
        <body className={inter.className}>
          <div className='wrapper'>{children}</div>
        </body>
      </html>
    </StoreProvider>
  );
}
